web:
  build: .
  dockerfile: Dockerfile_production
  working_dir: /app/user
  command: . /app/user/envs.docker.sh && node server.js
  expose: 
    - '3000'
    - '5432'
    - '6002'
  environment:
    - NODE_ENV=production
    - PORT=3000
    - PYTHONPATH=/app/user/python:$PYTHONPATH
  ports:
    - '80:3000'

worker:
  build: .
  dockerfile: Dockerfile_production
  working_dir: /app/user
  command: . /app/user/envs.docker.sh && node qserver.js
  expose: 
    - '3001'  
  environment:
    - PYTHONPATH=/app/user/python:$PYTHONPATH
    - PORT=3001
    
# You can share a data directory in development
# Make sure to adjust your DATA_DIR env
# Make sure to have access to antecedent rainfall thresholds and susceptibility maps 
# if you want to run the landslide model
# use -v HOST_VOLUME:CONTAINER_VOLUME command with docker run
#
development:
  build: .
  dockerfile: Dockerfile_production
  working_dir: /app/user
  command: bash
  expose: 
    - '3000'
    - '5432'
    - '6002'
  environment:
    - NODE_ENV=development
    - PORT=7465
    - PYTHONPATH=/app/user/python:$PYTHONPATH
  ports:
    - '7465:7465'
    - '7464:7464'
    
conda:
  build: .
  dockerfile: Dockerfile_conda


