{
    "application":      "OJO-Bot",
    "copyright":        "&copy; Vightel, 2013",
    "contact":          "Pat Cappelaere",
    "contact_mail":     "pat@cappelaere.com",
    "HOSTBASEURL":      "http://ojo-bot.herokuapp.com",
    "PORT":				80,
    "worldmapid":       "cappelaere.map-1d8e1acq",
    "send_email": 		0,
    "regions" : {
        "Global": {
            "bbox":         [-180, 60, 180, -60 ],
            "target":       [20, -80],
            "min_zoom":     2,
            "max_zoom":     12,
            "map_id":       "cappelaere.map-mx5g2tn3",
            "bucket":       "ojo-global",
            "ojotiler":     "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888"
        },
        "d02": {
            "name":		      "Central America",
            "bbox":         [-92.68, 6.17, -75.85, 19.08 ],
            "target":       [9.84, -84.14],
            "min_zoom":     7,
            "max_zoom":     18,
            "map_id":       "cappelaere.map-mx5g2tn3",
            "bucket":       "ojo-d2",
            "ojotiler":     "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888",
            "susmap":       "cappelaere.tbtvpyns"
        },
        "d03": {
            "name":		      "Hispaniola",
            "bbox":         [-74.94, 16.35, -64.98, 21.42 ],
            "target":       [18.89, -69.96],
            "min_zoom":     7,
            "max_zoom":	    18,
            "map_id":       "cappelaere.map-q4hdwmh3",
            "bucket":       "ojo-d3",
            "ojotiler":     "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888",
            "susmap":       "cappelaere.3uf4a15n"
        },
        "d04": {
            "name":		      "Namibia",
            "bbox":         [18, -21, 26, -17 ],
            "target":       [-18.12, 21.65],
            "min_zoom":     6,
            "max_zoom":	    18,
            "map_id":       "cappelaere.map-q4hdwmh3",
            "bucket":       "ojo-d4",
            "ojotiler":     "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888",
            "susmap":       "cappelaere.3uf4a15n"
        },
        "d05": {
            "name":		      "Malawi",
            "bbox":         [-74.94, 16.35, -64.98, 21.42 ],
            "target":       [-17.08, 35.22],
            "min_zoom":     7,
            "max_zoom":	    18,
            "map_id":       "cappelaere.map-q4hdwmh3",
            "bucket":       "ojo-d4",
            "ojotiler":     "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888",
            "susmap":       "cappelaere.3uf4a15n"
        }
    },
	
    "admins":   		[ "pat@cappelaere.com", "cappelaere@gmail.com" ],
    "support_email": 	["dalia.b.kirschbaum@nasa.gov","pat@geobliki.com"],
	
    "github":	{
      "user":				"vightel",
      "floods":			"gfc",
      "landslides":		"glc"
	},
	
	"nodes": [
          {
            "source": 		"dfo",
        		"href": 		"/opensearch",
        		"checked":  	false
        	},
        	{
        		"source": 		"digiglobe",
        		"href": 		"/opensearch",
        		"checked":  	false
        	},
        	{
        		"source": 		"ef5",
        		"href": 		"/opensearch",
        		"checked":  	true,
            "selected":   true
        	},
        	{
        		"source": 		"eo1_ali",
        		"href": 		"/opensearch",
        		"checked":  	false
        	},
          {
            "source": 		"landsat_8",
            "href": 		"/opensearch",
            "checked":  	false
          },
          {
            "source": 		"landslide_model",
            "href": 		"/opensearch",
            "checked":  	false
            },
          {
          	"source": 		"modis",
          	"href": 		"/opensearch",
          	"checked":  	false
          },
          {
            "source": 		"modis_lst",
            "href": 		"/opensearch",
            "checked":  	false
          },
          {
            "source": 		"ojo",
            "href": 		"/opensearch",
            "checked":  	false
          },
          {
            "source": 		"planet_labs",
            "href": 		"/opensearch",
            "checked":  	false
          },
        	{
              "source": 		"radarsat_2",
              "href": 		"/opensearch",
              "checked":  	false
          },
          {
              "source": 		"trmm",
              "href": 		"/opensearch",
              "checked": 		false
          }
	]
}

